### PR TITLE
Test latest ChefDK hab package version

### PR DESCRIPTION
**Pull request by afiune**
## Test latest ChefDK hab package version
To be able to promote ChefDK hab package to stable we need a new
scaffolding variable to accept the chef license at build time.

### New `scaffold_chef_license` variable

If this variable is not set, the user will have the following error:
```
   user-linux: Building
   user-linux: ERROR:

The Chef License must be accepted in your plan
through the variable 'scaffold_chef_license=<value>'.

More info: https://docs.chef.io/chef_license_accept.html

   user-linux: Build time: 0m33s
   user-linux: Exiting on error
```

### CODE REVIEW

**Comment by afiune** [comment]
The pipeline looks unhappy:
```
u must enter 'yes' or 'no' | 0s
-- | --
  | Prompt timed out. Use non-interactive flags or enter an answer within 60 seconds.
  | +---------------------------------------------+
  | Chef Development Kit cannot execute without accepting the license
  | user-linux-default: Build time: 2m41s
  | user-linux-default: Exiting on error
  | 🚨 Error: The command exited with status 1
```

It doesn't know how to accept the license. 🤔

**Comment by afiune** [comment]
Testing manually....

tenor-221330606

**Comment by afiune** [comment]
The test is actually discovering that we are not accepting or passing the acceptance of the license in the right way, I'll play a little bit with it and see if I can fix this.
```
user-linux-default: Building
+---------------------------------------------+
            Chef License Acceptance

Before you can continue, 3 product licenses
must be accepted. View the license at
https://www.chef.io/end-user-license-agreement/

Licenses that need accepting:
  * Chef Development Kit
  * Chef Infra Client
  * Chef InSpec

Do you accept the 3 product licenses (yes/no)?

>
```

**Comment by mike10010100** [comment]
Thank you so much for your efforts, this will hopefully solve the problem I've been having with installing certain cookbooks via policyfiles in effortless!

**Comment by afiune** [comment]
Until this point, we are testing that the promotion to the latest version of the ChefDK package succeeds. 

That version is `"chef/chef-dk/4.4.14/20190905060033"`
=> https://bldr.habitat.sh/#/pkgs/chef/chef-dk/latest

I am going to unpin the chef-dk version and ask for some review, to be explicit here,
this is a **breaking change** that will make all users accept the chef license inside every
habitat plan as follows:
```bash
scaffold_chef_license="accept-no-persist"
```

If that variable is not set, then we will display the following error:
```
   user-linux: Building
   user-linux: ERROR:

The Chef License must be accepted in your plan
through the variable 'scaffold_chef_license=<value>'.

More info: https://docs.chef.io/chef_license_accept.html

   user-linux: Build time: 0m33s
   user-linux: Exiting on error
```

**Comment by TheLunaticScripter** [comment]
@afiune Thank you so much for taking the time with this.

**Pull request merged**
